### ISSUE TITLE
魅族note3上面直接崩溃

### ISSUE THREAD

**Issue by youth5201314** [naturs/StatusBarHelper#3]
一运行软件魅族note3上面直接崩溃了，测试小米，vivo，三星都没问题。

**Comment by naturs** [comment]
@youth5201314 请问有没有错误日志

**Comment by youth5201314** [comment]
2016-08-01 09:13:21 
App Version: 1.0_1 
OS Version: 5.1_22 
Vendor: Meizu 
Model: m3 note 
CPU ABI: armeabi-v7a 

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setFitsSystemWindows(boolean)' on a null object reference   at com.gardenStuff.customview.statusbar.StatusBarHelperImpl.setActivityRootLayoutFitSystemWindowsInternal(StatusBarHelperImpl.java:54)  at com.gardenStuff.customview.statusbar.StatusBarHelperImpl21NormalFull.setColor(StatusBarHelperImpl21NormalFull.java:25)   at com.gardenStuff.customview.statusbar.StatusBarHelper.setColor(StatusBarHelper.java:73)   at com.gardenStuff.ui.SplashActivity.onTintStatusBar(SplashActivity.java:70)    at com.gardenStuff.BaseActivity.onCreate(BaseActivity.java:33)  at com.gardenStuff.ui.SplashActivity.onCreate(SplashActivity.java:32)   at android.app.Activity.performCreate(Activity.java:6059)   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2560)   ... 10 more

**Comment by naturs** [comment]
``` java
    protected void setActivityRootLayoutFitSystemWindowsInternal() {
        ViewGroup contentLayout = (ViewGroup) mActivity.findViewById(android.R.id.content);
        contentLayout.getChildAt(0).setFitsSystemWindows(isActivityRootLayoutFitSystemWindows());
    }
```

contentLayout.getChildAt(0)为空，你的SplashActivity是怎么写的？用了什么其他的库么

**Comment by youth5201314** [comment]
我的 SplashActivity没有问题，同样的代码其他手机都没有问题，
你应该考虑的是你的代码问题contentLayout.getChildAt(0)为空，
这里都没有加判断，我加了判断但是就没有效果了，
况且你的demo在魅族上都会报错。
